onebuttonweb:
  image: 945750603146.dkr.ecr.us-west-2.amazonaws.com/onebuttonweb:v2  
  cpu_shares: 100
  mem_limit: 134217728
  ports:
  - "80:80"
  entrypoint:
  - "/usr/sbin/apache2"
  - "-D"
  - "FOREGROUND"
